services:
  opensearch:
    image: opensearchproject/opensearch:3.6.0
    container_name: flowledger-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Vayupa2024wan
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "19200:9200"
      - "19600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - flowledger-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -k -u admin:Vayupa2024wan -f https://localhost:9200/_cluster/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 20

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.6.0
    container_name: flowledger-opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      OPENSEARCH_USERNAME: kibanaserver
      OPENSEARCH_PASSWORD: kibanaserver
      OPENSEARCH_SSL_VERIFICATIONMODE: none
    ports:
      - "15601:5601"
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - flowledger-network

volumes:
  opensearch-data:

networks:
  flowledger-network:
    name: flowledger-network