services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: flowledger-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Vayupa@2024@wan
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - minio-data:/data
    networks:
      - flowledger-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: flowledger-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - flowledger-network

  opensearch:
    image: opensearchproject/opensearch:3.6.0
    container_name: flowledger-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Vayupa2024wan
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "19200:9200"
      - "19600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - flowledger-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -k -u admin:Vayupa2024wan -f https://localhost:9200/_cluster/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 20

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.6.0
    container_name: flowledger-opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      OPENSEARCH_USERNAME: kibanaserver
      OPENSEARCH_PASSWORD: kibanaserver
      OPENSEARCH_SSL_VERIFICATIONMODE: none
    ports:
      - "15601:5601"
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - flowledger-network

volumes:
  opensearch-data:
  minio-data:

networks:
  flowledger-network:
    name: flowledger-network