package com.flowledger.auth.service;
import com.flowledger.auth.dto.*; import com.flowledger.auth.entity.*; import com.flowledger.auth.repository.*; import com.flowledger.common.exception.*; import com.flowledger.common.security.*; import com.flowledger.organization.entity.*; import com.flowledger.organization.repository.*; import lombok.extern.slf4j.Slf4j; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service @Slf4j public class AuthService {
 private final UserRepository users; private final RoleRepository roles; private final RefreshTokenRepository refreshTokens; private final OrganizationRepository organizations; private final OrganizationSettingsRepository settings; private final PasswordEncoder encoder; private final JwtService jwt; private final CustomUserDetailsService details; @Value("${flowledger.app.frontend-url}") private String frontendUrl;
 public AuthService(UserRepository users,RoleRepository roles,RefreshTokenRepository refreshTokens,OrganizationRepository organizations,OrganizationSettingsRepository settings,PasswordEncoder encoder,JwtService jwt,CustomUserDetailsService details){this.users=users;this.roles=roles;this.refreshTokens=refreshTokens;this.organizations=organizations;this.settings=settings;this.encoder=encoder;this.jwt=jwt;this.details=details;}
 @Transactional public LoginResponse login(LoginRequest r){User u=users.findByOrganizationIdAndEmailIgnoreCase(r.organizationId(),r.email()).orElseThrow(()->new UnauthorizedException("Invalid credentials")); if(!u.isActive()||!encoder.matches(r.password(),u.getPasswordHash()))throw new UnauthorizedException("Invalid credentials");u.setLastLoginAt(Instant.now());return tokens(u);}
 @Transactional public LoginResponse refresh(RefreshTokenRequest r){if(!jwt.isValid(r.refreshToken(),"refresh"))throw new UnauthorizedException("Invalid refresh token");String h=hash(r.refreshToken());RefreshToken t=refreshTokens.findByTokenHashAndRevokedFalse(h).filter(x->x.getExpiresAt().isAfter(Instant.now())).orElseThrow(()->new UnauthorizedException("Invalid refresh token"));t.setRevoked(true);User u=users.findByIdAndActiveTrue(t.getUserId()).orElseThrow(()->new UnauthorizedException("User unavailable")); LoginResponse result=tokens(u);t.setReplacedBy(refreshTokens.findByTokenHashAndRevokedFalse(hash(result.refreshToken())).orElseThrow().getId());return result;}
 @Transactional public void logout(String token){refreshTokens.findByTokenHashAndRevokedFalse(hash(token)).ifPresent(t->t.setRevoked(true));}
 @Transactional public void forgotPassword(ForgotPasswordRequest r){User u=users.findByOrganizationIdAndEmailIgnoreCase(r.organizationId(),r.email()).orElseThrow(()->new ResourceNotFoundException("User not found"));String token=UUID.randomUUID().toString();u.setPasswordResetToken(hash(token));u.setPasswordResetExpiry(Instant.now().plus(Duration.ofHours(1)));log.info("Password reset link: {}/reset-password?token={}",frontendUrl,token);}
 @Transactional public void resetPassword(ResetPasswordRequest r){User u=users.findByPasswordResetToken(hash(r.token())).filter(x->x.getPasswordResetExpiry().isAfter(Instant.now())).orElseThrow(()->new BusinessException("Invalid or expired reset token"));u.setPasswordHash(encoder.encode(r.newPassword()));u.setPasswordResetToken(null);u.setPasswordResetExpiry(null);refreshTokens.deleteByUserId(u.getId());}
 @Transactional public void changePassword(UUID userId,ChangePasswordRequest r){User u=users.findById(userId).orElseThrow(()->new ResourceNotFoundException("User not found"));if(!encoder.matches(r.currentPassword(),u.getPasswordHash()))throw new BusinessException("Current password is incorrect");u.setPasswordHash(encoder.encode(r.newPassword()));refreshTokens.deleteByUserId(userId);}
 @Transactional public LoginResponse registerOrganization(RegisterOrganizationRequest r){Organization o=new Organization();o.setName(r.organizationName());o.setEmail(r.email());organizations.save(o);OrganizationSettings s=new OrganizationSettings();s.setOrganizationId(o.getId());settings.save(s);Role role=roles.findByCode("ORGANIZATION_ADMIN").orElseThrow(()->new BusinessException("Organization admin role is unavailable"));User u=new User();u.setOrganizationId(o.getId());u.setEmail(r.email());u.setPasswordHash(encoder.encode(r.password()));u.setFirstName(r.firstName());u.setLastName(r.lastName());u.setPhone(r.phone());u.getRoles().add(role);users.save(u);return tokens(u);}
 private LoginResponse tokens(User u){UserPrincipal p=details.load(u.getId());String access=jwt.createAccessToken(p), refresh=jwt.createRefreshToken(p);RefreshToken t=new RefreshToken();t.setUserId(u.getId());t.setTokenHash(hash(refresh));t.setExpiresAt(Instant.now().plus(Duration.ofDays(14)));refreshTokens.save(t);return new LoginResponse(access,refresh,jwt.accessExpirySeconds(),response(u));}
 private UserResponse response(User u){return new UserResponse(u.getId(),u.getOrganizationId(),u.getEmail(),u.getFirstName(),u.getLastName(),u.getRoles().stream().map(Role::getCode).collect(java.util.stream.Collectors.toSet()));}
 private String hash(String value){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
