package com.flowledger.accounting.domain;

public enum AccountSubType {
    CASH,
    BANK,
    ACCOUNTS_RECEIVABLE,
    ACCOUNTS_PAYABLE,
    INVENTORY,
    FIXED_ASSET,
    CURRENT_ASSET,
    CURRENT_LIABILITY,
    LONG_TERM_LIABILITY,
    CAPITAL,
    RETAINED_EARNINGS,
    SALES,
    PURCHASE,
    DIRECT_INCOME,
    INDIRECT_INCOME,
    DIRECT_EXPENSE,
    INDIRECT_EXPENSE,
    TAX_RECEIVABLE,
    TAX_PAYABLE,
    COST_OF_GOODS_SOLD,
    ROUND_OFF,
    DISCOUNT_ALLOWED,
    DISCOUNT_RECEIVED
}
