package com.flowledger.notification;

public enum NotificationType {
    PAYMENT_REMINDER,
    INVOICE,
    PASSWORD_RESET,
    USER_INVITATION,
    LEAD_FOLLOW_UP,
    MARKETING,
    SYSTEM,
    WORKFLOW_APPROVAL,
    SHIPMENT_ACTIVITY,
    SHIPMENT_ASSIGNED,
    SHIPMENT_DISPATCHED,
    SHIPMENT_CHECKPOINT,
    SHIPMENT_DELAYED,
    SHIPMENT_DELIVERED,
    TRANSPORT_COMPLIANCE_EXPIRY
}
