package com.flowledger.accounting.bootstrap;

import com.flowledger.accounting.domain.AccountSubType;
import com.flowledger.accounting.domain.AccountType;
import com.flowledger.accounting.domain.SystemAccountKey;

/**
 * Single source of truth for the default organization Chart of Accounts.
 * Group headers use {@code GRP-*} codes; leaf accounts preserve posting codes used by the engine.
 */
public final class ChartOfAccountsTemplate {
    private ChartOfAccountsTemplate() {}

    public record Node(
            String code,
            String name,
            AccountType accountType,
            AccountSubType accountSubType,
            SystemAccountKey systemAccountKey,
            String parentCode,
            boolean groupHeader,
            boolean allowManualPosting) {}

    public static final java.util.List<Node> NODES = java.util.List.of(
            new Node("GRP-ASSET", "Assets", AccountType.ASSET, null, null, null, true, false),
            new Node("1000", "Cash", AccountType.ASSET, AccountSubType.CASH, SystemAccountKey.CASH, "GRP-ASSET", false, true),
            new Node("1010", "Bank", AccountType.ASSET, AccountSubType.BANK, SystemAccountKey.BANK, "GRP-ASSET", false, true),
            new Node(
                    "1100",
                    "Accounts Receivable",
                    AccountType.ASSET,
                    AccountSubType.ACCOUNTS_RECEIVABLE,
                    SystemAccountKey.ACCOUNTS_RECEIVABLE,
                    "GRP-ASSET",
                    false,
                    true),
            new Node(
                    "1200",
                    "Inventory",
                    AccountType.ASSET,
                    AccountSubType.INVENTORY,
                    SystemAccountKey.INVENTORY,
                    "GRP-ASSET",
                    false,
                    true),
            new Node(
                    "1300",
                    "Input CGST",
                    AccountType.ASSET,
                    AccountSubType.TAX_RECEIVABLE,
                    SystemAccountKey.INPUT_CGST,
                    "GRP-ASSET",
                    false,
                    true),
            new Node(
                    "1310",
                    "Input SGST",
                    AccountType.ASSET,
                    AccountSubType.TAX_RECEIVABLE,
                    SystemAccountKey.INPUT_SGST,
                    "GRP-ASSET",
                    false,
                    true),
            new Node(
                    "1320",
                    "Input IGST",
                    AccountType.ASSET,
                    AccountSubType.TAX_RECEIVABLE,
                    SystemAccountKey.INPUT_IGST,
                    "GRP-ASSET",
                    false,
                    true),
            new Node("GRP-LIABILITY", "Liabilities", AccountType.LIABILITY, null, null, null, true, false),
            new Node(
                    "2000",
                    "Accounts Payable",
                    AccountType.LIABILITY,
                    AccountSubType.ACCOUNTS_PAYABLE,
                    SystemAccountKey.ACCOUNTS_PAYABLE,
                    "GRP-LIABILITY",
                    false,
                    true),
            new Node(
                    "2100",
                    "Output CGST",
                    AccountType.LIABILITY,
                    AccountSubType.TAX_PAYABLE,
                    SystemAccountKey.OUTPUT_CGST,
                    "GRP-LIABILITY",
                    false,
                    true),
            new Node(
                    "2110",
                    "Output SGST",
                    AccountType.LIABILITY,
                    AccountSubType.TAX_PAYABLE,
                    SystemAccountKey.OUTPUT_SGST,
                    "GRP-LIABILITY",
                    false,
                    true),
            new Node(
                    "2120",
                    "Output IGST",
                    AccountType.LIABILITY,
                    AccountSubType.TAX_PAYABLE,
                    SystemAccountKey.OUTPUT_IGST,
                    "GRP-LIABILITY",
                    false,
                    true),
            new Node("GRP-EQUITY", "Equity", AccountType.EQUITY, null, null, null, true, false),
            new Node(
                    "3000",
                    "Capital",
                    AccountType.EQUITY,
                    AccountSubType.CAPITAL,
                    SystemAccountKey.CAPITAL,
                    "GRP-EQUITY",
                    false,
                    true),
            new Node(
                    "3100",
                    "Retained Earnings",
                    AccountType.EQUITY,
                    AccountSubType.RETAINED_EARNINGS,
                    SystemAccountKey.RETAINED_EARNINGS,
                    "GRP-EQUITY",
                    false,
                    true),
            new Node("GRP-REVENUE", "Income", AccountType.REVENUE, null, null, null, true, false),
            new Node(
                    "4000",
                    "Sales",
                    AccountType.REVENUE,
                    AccountSubType.SALES,
                    SystemAccountKey.SALES,
                    "GRP-REVENUE",
                    false,
                    true),
            new Node(
                    "4100",
                    "Other Income",
                    AccountType.REVENUE,
                    AccountSubType.INDIRECT_INCOME,
                    SystemAccountKey.OTHER_INCOME,
                    "GRP-REVENUE",
                    false,
                    true),
            new Node(
                    "4200",
                    "Discount Received",
                    AccountType.REVENUE,
                    AccountSubType.DISCOUNT_RECEIVED,
                    SystemAccountKey.DISCOUNT_RECEIVED,
                    "GRP-REVENUE",
                    false,
                    true),
            new Node(
                    "4300",
                    "Round Off Income",
                    AccountType.REVENUE,
                    AccountSubType.ROUND_OFF,
                    SystemAccountKey.ROUND_OFF_INCOME,
                    "GRP-REVENUE",
                    false,
                    true),
            new Node("GRP-EXPENSE", "Expense", AccountType.EXPENSE, null, null, null, true, false),
            new Node(
                    "5000",
                    "Purchases",
                    AccountType.EXPENSE,
                    AccountSubType.PURCHASE,
                    SystemAccountKey.PURCHASE,
                    "GRP-EXPENSE",
                    false,
                    true),
            new Node(
                    "5100",
                    "Cost of Goods Sold",
                    AccountType.EXPENSE,
                    AccountSubType.COST_OF_GOODS_SOLD,
                    SystemAccountKey.COGS,
                    "GRP-EXPENSE",
                    false,
                    true),
            new Node(
                    "5200",
                    "Operating Expenses",
                    AccountType.EXPENSE,
                    AccountSubType.INDIRECT_EXPENSE,
                    SystemAccountKey.OPERATING_EXPENSES,
                    "GRP-EXPENSE",
                    false,
                    true),
            new Node(
                    "5300",
                    "Discount Allowed",
                    AccountType.EXPENSE,
                    AccountSubType.DISCOUNT_ALLOWED,
                    SystemAccountKey.DISCOUNT_ALLOWED,
                    "GRP-EXPENSE",
                    false,
                    true),
            new Node(
                    "5400",
                    "Round Off Expense",
                    AccountType.EXPENSE,
                    AccountSubType.ROUND_OFF,
                    SystemAccountKey.ROUND_OFF_EXPENSE,
                    "GRP-EXPENSE",
                    false,
                    true));
}
